export const ARTWORK_OUTPUT_SIZE = 1024;
export const ARTWORK_PREVIEW_QUALITY = 0.92;
export const CROP_VIEWPORT_HEIGHT_RATIO = 0.75;
export const MAX_CROP_HEIGHT = 1600;
export const MAX_CROP_WIDTH = 1600;
